version: '3.9'

x-vmangos-shared-conf: &vmangos-shared-conf
  # environment:

  volumes:
    - "./etc:/opt/etc:rw"
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"
    - "./server:/opt/server:rw"
  restart: unless-stopped
  env_file:
  - .env
  tty: true

x-build-shared-conf: &build-shared-conf
  dockerfile: Dockerfile
  args:
    USER_ID: ${USER_ID:-0}
    GROUP_ID: ${GROUP_ID:-0}

services:

  compile:
    image: vmangos:compile
    container_name: vmangos-compile
    build:
      context: docker/compile
      <<: *build-shared-conf
      args:
        DOCKER_BUILDKIT: 1
    <<: *vmangos-shared-conf
    restart: "no"

  mangosd:
    image: vmangos:mangosd
    container_name: vmangos-mangosd
    build:
      context: docker/mangosd
      <<: *build-shared-conf
    ports:
      - "3443:3443"
      - "3444:3444" 
      - "7878:7878"
      - "8085:8085"
    <<: *vmangos-shared-conf
    
  mariadb:
    image: vmangos:mariadb
    container_name: vmangos-mariadb
    hostname: mariadb
    build:
      context: docker/mariadb
      <<: *build-shared-conf
    ports:
      - "3306:3306"
    <<: *vmangos-shared-conf

  phpmyadmin:
    image: phpmyadmin
    container_name: vmangos-phpmyadmin
    ports:
      - "8080:80"
    restart: "no"
    depends_on:
      - mariadb
    env_file:
      - .env

  realmd:
    image: vmangos:realmd
    container_name: vmangos-realmd
    build:
      context: docker/realmd
      <<: *build-shared-conf
    ports:
      - "3724:3724"
    <<: *vmangos-shared-conf

  web:
    image: vmangos:web
    container_name: vmangos-web
    build:
      context: docker/web
      <<: *build-shared-conf
    ports: 
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - ./web:/var/www/html
      - ./docker/web/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/web/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      - mariadb

networks:
  default:
    name: vmangos-server-network
